version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli-node-browsers

    steps:
      - checkout
      - run: sudo apt-get install -y libzip-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      - run: php bin/phpunit
